services:
  - type: web
    name: astrobsm-oracle-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && cd ../frontend/react-app && npm install --legacy-peer-deps && chmod +x ./node_modules/.bin/react-scripts && npm run build && cp -r build ../../backend/app/static && alembic -c alembic.ini upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        value: postgresql://mdcan_bdm2025enugu_user:SqqPDfWX6vw2dYmOiEexSq64BglxF9NZ@dpg-d0ummsbe5dus739ns56g-a/mdcan_bdm2025enugu
      - key: SECRET_KEY
        value: <your_secret_key>
    plan: free
